export default {
  login: 'matthewyee92',
  id: 6599979,
  node_id: 'MDQ6VXNlcjY1OTk5Nzk=',
  avatar_url: 'https://avatars2.githubusercontent.com/u/6599979?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/matthewyee92',
  html_url: 'https://github.com/matthewyee92',
  followers_url: 'https://api.github.com/users/matthewyee92/followers',
  following_url: 'https://api.github.com/users/matthewyee92/following{/other_user}',
  gists_url: 'https://api.github.com/users/matthewyee92/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/matthewyee92/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/matthewyee92/subscriptions',
  organizations_url: 'https://api.github.com/users/matthewyee92/orgs',
  repos_url: 'https://api.github.com/users/matthewyee92/repos',
  events_url: 'https://api.github.com/users/matthewyee92/events{/privacy}',
  received_events_url: 'https://api.github.com/users/matthewyee92/received_events',
  type: 'User',
  site_admin: false,
  name: 'Matthew Yee',
  company: '@Hack Reactor',
  blog: 'https://matthewyee.dev',
  location: 'Seattle, WA',
  email: null,
  hireable: true,
  bio: null,
  public_repos: 53,
  public_gists: 4,
  followers: 248,
  following: 12,
  created_at: '2014-02-05T23:22:59Z',
  updated_at: '2019-04-17T03:18:31Z',
};
